import Head from "next/head";

import Banner from "../sections/Banner";
import Cta from "../sections/Cta";
import Features from "../sections/Features";

export default function Home() {
  return (
    <>
      <Head>
        <title>Nstant Food Delivery | Trendy food delivery platform</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner />
      <Features />
      <Cta />
    </>
  );
}
